import { signup } from "../actions/auth";

export const languages = {
    english: {
      hello: 'Hello',
      error_email:'Please enter a valid email address',
      email:'E-Mail',
      password:"Password",
      error_password:'Please enter a valid password.',
      signup:"Sign up",
      login:"Log in",
      acc:"Do you have an account?",
      noacc:"I dont have a account.",
      e: "An error has occurred!",
      tit: "Title",
      e_title: "Please enter a valid title!",
      url_i: 'Image URL',
      e_url: "Please enter a valid image url!",
      price: "Price",
      e_price: "Please enter a valid price!",
      desc: "Description",
      e_desc: "Please enter a valid description!",
      change_p: "Change post",
      add_p: "Add post",
      e_data: "Wrong data!",
      e_form: "Please check for errors in the form.",
      delete_m: "Are you sure?",
      delete_m2: "Do you really want to delete this post?",
      nopost: "No posts found. Start adding some!",
      del: "Delete",
      chang: "Change",
      your_p: "Your Posts",
      buy: "Book",
      rez: "Your bookings ",
      e_2: "Something went wrong!",
      norez: "No past bookings found!",
      add_rez: "Add to booking",
      nopost: "No posts found. Start adding some!",
      details_m: "View details",
      all_p: "All posts",
      log_out: "Logout",
  
      show:'Show',
      hide:"Hide",

    },
    albanian: {
      hello: 'Miremengjes!',
      error_email:'Ju lutemi shkruani një adresë të vlefshme emaili',
      email:'E-Mail',
      password:"Fjalekalimi",
      error_password:'Ju lutemi shkruani një fjalëkalim të vlefshëm.',
      signup:"Regjistrohuni",
      login:"Hyni",
      acc:"A keni një llogari?",
      noacc:"Nuk kam nje llogari",
      e:"Një gabim ka ndodhur!",
      tit:"Titulli",
      e_title:"Ju lutemi shkruani një titull të vlefshëm!",
      url_i:'URL e imazhit',
      e_url:"Ju lutemi shkruani një url të vlefshme të imazhit!",
      price:"Çmimi",
      e_price:"Ju lutemi shkruani një çmim të vlefshëm!",
      desc:"Përshkrim",
      e_desc:"Ju lutemi shkruani një përshkrim të vlefshëm!",
      change_p:"Ndrysho postin",
      add_p:"Shtoni postin",
      e_data:"Të dhëna të gabuara!",
      e_form:"Ju lutemi kontrolloni gabimet në formë.",
      delete_m:"A jeni i sigurt?",
      delete_m2:"A doni vërtet ta fshini këtë post?",
      nopost:"Nuk u gjet asnjë post. Filloni të shtoni disa!",
      del:"Fshini",
      chang:"Ndryshoni",
      your_p:"Postet e tua",
      buy:"Rezervoni",
      rez:"Rezervimet e tua",
      e_2:"Dicka shkoi keq!",
      norez:"Nuk u gjet asnjë rezervim i kaluar!",
      add_rez:"Shtoni ne rezervim",
      nopost:"Nuk u gjet asnjë post. Filloni të shtoni disa!",
      details_m:"Shiko detajet",
      all_p:"Te gjitha postet",
      log_out:"Dilni",
     
      show:'Me shume',
      hide:"Mbyll",
    
    }
  }